INSERT INTO `shop_front`.`product_tbl` (`product_title`, `product_cost`, `product_status`, `product_description`, `IDcreator`, `product_entry_date`) VALUES ('The First Entry', '32.51', 'active', 'This is the first entry product to the system. It will not be stayying here for long.', '6', '65584165');
INSERT INTO `shop_front`.`product_tbl` (`product_title`, `product_cost`, `product_status`, `product_description`, `IDcreator`, `product_entry_date`) VALUES ('The Second Entry', '85.48', 'active', 'This is the just some change up of infomation.', '6', '68684165');
INSERT INTO `shop_front`.`product_tbl` (`product_title`, `product_cost`, `product_status`, `product_description`, `IDcreator`, `product_entry_date`) VALUES ('My Web App', '900.00', 'active', 'The app is built to make the life of others better but more so to make me money', '5', '56841541');
INSERT INTO `shop_front`.`product_tbl` (`product_title`, `product_cost`, `product_status`, `product_description`, `IDcreator`, `product_entry_date`) VALUES ('It was a bear', '25.00', 'active', 'The hard part now is there is so much informatin to put in that it is hard to work out how to set everything up', '5', '54631658');
INSERT INTO `shop_front`.`product_tbl` (`product_title`, `product_cost`, `product_status`, `product_description`, `IDcreator`, `product_entry_date`) VALUES ('The Forth', '85.00', 'active', 'Its so much fun doing all this hard work to know that its never going to come to anything in the end of the day', '6', '6546949615');
INSERT INTO `shop_front`.`product_tbl` (`product_title`, `product_cost`, `product_status`, `product_description`, `IDcreator`, `product_entry_date`) 
VALUES ('Check Length', '32.00', 'active', 'Its so much fun doing all this hard work to know that its never going to come to anything in the end of the day. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.

This is the first entry product to the system. It will not be stayying here for long.', '3', '65949615');
